name: iProtector
author: LDX
version: 3.1.1
main: LDX\iProtector\Main
load: POSTWORLD
api: [3.0.0]
commands:
  area:
    description: ""
    usage: "/area <pos1/pos2/create/list/here/flag/whitelist/delete>"
    permission: iprotector.command.area
permissions:
  iprotector:
    description: ""
    default: false
    children:
      iprotector.access:
        description: ""
        default: op
      iprotector.command:
        description: ""
        default: false
        children:
          iprotector.command.area:
            description: ""
            default: op
            children:
              iprotector.command.area.pos1:
                description: ""
                default: op
              iprotector.command.area.pos2:
                description: ""
                default: op
              iprotector.command.area.create:
                description: ""
                default: op
              iprotector.command.area.list:
                description: ""
                default: op
              iprotector.command.area.here:
                description: ""
                default: op
              iprotector.command.area.flag:
                description: ""
                default: op
              iprotector.command.area.delete:
                description: ""
                default: op
              iprotector.command.area.whitelist:
                description: ""
                default: op
              iprotector.command.area.tp:
                description: ""
                default: op
              iprotector.command.area.list:
                description: ""
                default: op
